spring:
  application:
    name: auth-service
  profiles:
    active: dev

server:
  port: 8081

cors:
  allowed-origins: "https://markup-landing.vercel.app"

springdoc:
  api-docs.path: /v3/api-docs
  swagger-ui.path: /swagger-ui/index.html

jwt:
  secret: "mi-super-secret-key-para-desarrollo-con-minimo-32-caracteres-de-longitud"
  expiration: 86400000
